In [1]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv')

data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [2]:
X = data.drop('Outcome', axis=1)
y = data['Outcome']


In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)


In [4]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)


LogisticRegression(max_iter=1000)

In [5]:
y_scores = model.predict_proba(X_test)[:,1]


In [6]:
y_scores

array([0.049539  , 0.17459099, 0.09362339, 0.25507761, 0.63548024,
       0.11671372, 0.06566903, 0.4219197 , 0.0486621 , 0.57564701,
       0.33875915, 0.41304941, 0.69853657, 0.19963021, 0.02001671,
       0.82470139, 0.86657395, 0.03101209, 0.25510431, 0.89492846,
       0.95245844, 0.83474506, 0.11741683, 0.44670322, 0.08923741,
       0.06883141, 0.65118348, 0.41197555, 0.17860989, 0.28690449,
       0.24546578, 0.43902898, 0.00942498, 0.24259998, 0.35171462,
       0.96164357, 0.34357377, 0.80926758, 0.29380391, 0.0508346 ,
       0.18184543, 0.08672141, 0.42227405, 0.18738207, 0.03011659,
       0.03949444, 0.24741934, 0.42783665, 0.10529037, 0.37968533,
       0.99355621, 0.1066618 , 0.39100185, 0.76881604, 0.3686589 ,
       0.45775787, 0.95035471, 0.41993707, 0.39152713, 0.04376164,
       0.37292047, 0.90129902, 0.8817627 , 0.88843223, 0.33083604,
       0.06931771, 0.95265128, 0.20053148, 0.26054372, 0.35463528,
       0.10358789, 0.0816807 , 0.45044142, 0.09221122, 0.08649

In [ ]:
y_scores

array([0.2758503 , 0.18842069, 0.11448981, 0.16368795, 0.4715251 ,
       0.44170194, 0.01545458, 0.6605503 , 0.54136875, 0.77717331,
       0.25601769, 0.89728056, 0.33614441, 0.30308996, 0.08199125,
       0.38084702, 0.13934778, 0.07482402, 0.86665798, 0.5613247 ,
       0.20835836, 0.07736815, 0.53982239, 0.09456509, 0.53967271,
       0.88554708, 0.1243389 , 0.03014779, 0.25152025, 0.11579709,
       0.91109793, 0.8706549 , 0.76531008, 0.83743011, 0.6165898 ,
       0.68350024, 0.96806648, 0.24353318, 0.51154452, 0.73599347,
       0.06983745, 0.59378797, 0.58351287, 0.32753119, 0.02760688,
       0.50239856, 0.63926574, 0.22539934, 0.36059905, 0.95624662,
       0.04890383, 0.66102112, 0.81174894, 0.24555107, 0.09320651,
       0.04152459, 0.77799846, 0.00570139, 0.40866977, 0.75690546,
       0.7413723 , 0.35188999, 0.19230059, 0.20514197, 0.0768586 ,
       0.6270294 , 0.050907  , 0.73293779, 0.03690838, 0.71583657,
       0.67525971, 0.07016837, 0.18115086, 0.11426867, 0.09119

In [7]:
from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_test, y_scores)

In [8]:
thresholds

array([       inf, 0.99355621, 0.95265128, 0.95245844, 0.82470139,
       0.76881604, 0.7619787 , 0.68387983, 0.67531062, 0.67422131,
       0.65118348, 0.65080946, 0.63548024, 0.58631304, 0.57564701,
       0.56976124, 0.5251727 , 0.47019945, 0.46128965, 0.45044142,
       0.43902898, 0.4386454 , 0.42227405, 0.41993707, 0.41304941,
       0.41197555, 0.4047921 , 0.37968533, 0.3686589 , 0.31020653,
       0.30880322, 0.27772675, 0.27206946, 0.25510431, 0.25507761,
       0.24741934, 0.24546578, 0.23667508, 0.22885393, 0.18184543,
       0.17860989, 0.17459099, 0.17326554, 0.14638876, 0.1407579 ,
       0.11671372, 0.11494173, 0.11000427, 0.1066618 , 0.08923741,
       0.08672141, 0.02001671, 0.01931281, 0.00160788])

In [9]:
import plotly.graph_objects as go
import numpy as np


# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name='ROC curve'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center'
)


# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=False
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


In [ ]:
# Assume that fpr, tpr, thresholds have already been calculated
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
print("Optimal threshold is:", optimal_threshold)


Optimal threshold is: 0.5503810234218872


In [10]:
import plotly.graph_objects as go
import numpy as np
from sklearn.metrics import roc_auc_score

# Assuming fpr, tpr, thresholds are already calculated as before
fpr, tpr, thresholds = roc_curve(y_test, y_scores)

# Calculate the AUC (Area Under the Curve)
roc_auc = roc_auc_score(y_test, y_scores)

# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name=f'ROC curve (Area = {roc_auc:.2f})'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


In [11]:
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler

# Assuming that X_train, X_test, y_train, y_test are already defined

# SVM requires feature scaling for better performance
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression model
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
lr_scores = lr_model.predict_proba(X_test)[:,1]

# SVM model
svm_model = SVC(probability=True)
svm_model.fit(X_train_scaled, y_train)
svm_scores = svm_model.predict_proba(X_test_scaled)[:,1]

# Generate ROC curve data for logistic regression model
lr_fpr, lr_tpr, lr_thresholds = roc_curve(y_test, lr_scores)
lr_auc = roc_auc_score(y_test, lr_scores)

# Generate ROC curve data for SVM model
svm_fpr, svm_tpr, svm_thresholds = roc_curve(y_test, svm_scores)
svm_auc = roc_auc_score(y_test, svm_scores)

# Generate a trace for the Logistic Regression ROC curve
trace0 = go.Scatter(
    x=lr_fpr,
    y=lr_tpr,
    mode='lines',
    name=f'Logistic Regression (Area = {lr_auc:.2f})'
)

# Generate a trace for the SVM ROC curve
trace1 = go.Scatter(
    x=svm_fpr,
    y=svm_tpr,
    mode='lines',
    name=f'SVM (Area = {svm_auc:.2f})'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()
