**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
arr=np.nan*np.empty(10)
arr[4]=1
arr

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
a=int(input("Enter a: "))
b=int(input("Enter b: "))
arr=np.random.random(size=(a,b))
print(f"{arr}\n\nMean: {arr.mean()}")

Enter a: 3
Enter b: 4
[[0.22091029 0.80883966 0.98927239 0.77440888]
 [0.18245244 0.80917922 0.24493679 0.06785205]
 [0.45937352 0.27494064 0.09783737 0.14219634]]

Mean: 0.42268330041738444


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
arr = np.ones(shape=(4,4), dtype=int)
arr[1:-1,1:-1]=0
arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
arr = np.linspace(0,1,12)[1:-1]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here
arr= np.zeros((5,5))
arr+= np.arange(5)
print(arr)

print()

arr1=np.tile(np.arange(5),(5,1))
arr1

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]



array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
a = np.random.randint(1, 100, (10, 2))
p = np.array([2,3])
distance = np.sqrt(np.sum((a-p)**2, axis=1)).astype(int)
distance

array([ 33,  31,  50,  46,  93,  98, 105,  81,  70,  35])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
index = np.unravel_index(99, (6, 7, 8))
print(index)


(1, 5, 3)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
num = input("Enter numbers: ").strip().split()
print(num)
arr = np.array(num[::-1],dtype=float)
print(arr)

Enter numbers: 1 2 3 4 
['1', '2', '3', '4']
[4. 3. 2. 1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
arr=np.array([])
arr1=np.array([1, 2])
print(f"elements_count :{arr.size}")
print(f"elements_count :{arr1.size}")


elements_count :0
elements_count :2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here
def softmax(arr):
  if type(arr)!=np.ndarray:
    raise TypeError("Requires Numpy Array")
  elif arr.ndim > 1:
    raise TypeError("Require 1-D Array")
  s=np.sum(np.exp(arr))
  return np.exp(arr)/s


softmax(np.array([86.03331084,37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here
def stackArray(array1,*args):
  if type(array1)!=np.ndarray and type(*args)!=np.ndarray:
    raise TypeError("requires numpy array")
  arr=np.vstack((array1,*args))
  return arr

a= np.array([[0 ,1, 2, 3, 4],[5, 6, 7, 8, 9]])

b= np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])

c= np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
 [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

stackArray(a,b,c)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [3]:
#Code here

def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError

    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

    end = end.split("-")
    end_last = int(end[-1]) + 1

    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff< 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month< 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = "-".join(end)
    return np.arange(start, end, dtype="datetime64[D]")    # Use arange() to generate all dates between start and end
date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
a= np.random.randint(10,100, (3,4))
output = a-a.mean(axis=1,keepdims=True)
output


array([[ 22.75,   6.75,  -3.25, -26.25],
       [-13.  , -14.  ,  33.  ,  -6.  ],
       [-35.5 ,  42.5 , -42.5 ,  35.5 ]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [16]:
import numpy as np

arr = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
arr = arr[:,[1,0]]
arr

array([[2, 1],
       [3, 2],
       [4, 3],
       [5, 4]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here
a=np.arange(1,10)
a[a%2==1]=-1
a

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c=np.vstack((a,b))
print(c.max(axis=0))

a[b>a] = b[a<b]
a

[6 3 1 7 8]


array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1)

[[4623 2804   87 6575 7981]
 [9959 6788  111 9551 2757]
 [4587 5261 4034  287 6393]
 [3961 3776 7189 9912 1964]
 [6887 5660  810 1456 7615]
 [1710 4293 2675 7064 9500]
 [8927 4923 1900 7242 4919]
 [8305 1986  306 7451 2508]]


In [ ]:
#Code here
max = arr1.max()
min = arr1.min()
arr2 = (arr1-min)/(max-min)
arr2

array([[0.45948136, 0.27522285, 0.        , 0.65721232, 0.79963533],
       [1.        , 0.67878849, 0.00243112, 0.95867099, 0.27046191],
       [0.45583468, 0.52410859, 0.39981767, 0.02025932, 0.63877634],
       [0.39242301, 0.37368314, 0.71940843, 0.99523906, 0.19013371],
       [0.68881686, 0.56452593, 0.07323744, 0.13867504, 0.76256078],
       [0.16440438, 0.42605348, 0.26215559, 0.70674635, 0.95350486],
       [0.89546191, 0.48987034, 0.18365073, 0.72477715, 0.48946515],
       [0.83245543, 0.19236224, 0.02218395, 0.74594814, 0.24523906]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here
def nthLargest(arr,n):
  if n>len(arr):
    raise IndexError("n is way out of index")
  arr.sort()
  return arr[n]

nthLargest(np.array([12,34,40,7,1,0]),1)

1

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here
a = np.array([1,2,3])
print(np.repeat(a,3))
print(np.tile(a,3))


[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [ ]:
np.hstack((np.repeat(a,3),np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9])
sorted_arr = np.sort(arr)

print("Original array:", arr)      # [3, 1, 4, 1, 5, 9]
print("Sorted array:", sorted_arr) # [1, 1, 3, 4, 5, 9]


Original array: [3 1 4 1 5 9]
Sorted array: [1 1 3 4 5 9]


In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9])
arr.sort()
